# Generated by Django 4.0.5 on 2022-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_lead_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
