# Generated by Django 4.0.6 on 2022-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_lead_converted_date_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
