# Generated by Django 4.0.6 on 2022-07-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_lead_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted_date',
        ),
    ]
